-- Migration 0008: Seed all members + guestbook + news
-- Generated from data.ts MEMBERS array + seed.ts guestbook
-- Idempotent — uses ON CONFLICT (slug) DO UPDATE. Safe to run multiple times.
-- Run this in Supabase SQL Editor to seed all data without bun.

BEGIN;

-- Aldi (THE FOUNDER)
INSERT INTO "Member" ("slug","name","nick","role","img","color","highlight","bio","tagline","quote","funFactsJson","element","joinYear","statsJson","socialsJson","taglineCareer","location","availability","educationJson","workHistoryJson","skillsJson","hidden","order","createdAt","updatedAt") VALUES ('aldi','Raynaldi','Aldi','THE FOUNDER','','bg-[#ff4d4d]','text-[#ff4d4d]','Titik nol dari mana semua orbit dimulai. **Sang pendiri** yang menyalakan percikan pertama dan tak pernah membiarkannya padam, sejauh apapun anggota lainnya pergi.','Lit the first spark. Never let it die.','Sejauh apapun kita terbang, gravitasi pertemanan selalu menarik kita kembali ke orbit yang sama.',$$["Selalu jadi orang pertama yang online di grup","Pemilik rekor 'paling sering ngajak nongkrong'","Punya playlist spotify untuk tiap mood anggota","Tidak pernah telat — kecuali sengaja"]$$,'FIRE','2020',$$[{"label":"STR","value":"16"},{"label":"DEX","value":"12"},{"label":"CON","value":"15"},{"label":"INT","value":"13"},{"label":"WIS","value":"10"},{"label":"CHA","value":"14"}]$$,$$[{"label":"INSTAGRAM","href":"#"},{"label":"X_TWITTER","href":"#"},{"label":"DISCORD","href":"#"}]$$,'','','EMPLOYED',$$[]$$,$$[]$$,$$[]$$,false,0,NOW(),NOW()) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","nick"=EXCLUDED."nick","role"=EXCLUDED."role","img"=EXCLUDED."img","color"=EXCLUDED."color","highlight"=EXCLUDED."highlight","bio"=EXCLUDED."bio","tagline"=EXCLUDED."tagline","quote"=EXCLUDED."quote","funFactsJson"=EXCLUDED."funFactsJson","element"=EXCLUDED."element","joinYear"=EXCLUDED."joinYear","statsJson"=EXCLUDED."statsJson","socialsJson"=EXCLUDED."socialsJson","taglineCareer"=EXCLUDED."taglineCareer","location"=EXCLUDED."location","availability"=EXCLUDED."availability","educationJson"=EXCLUDED."educationJson","workHistoryJson"=EXCLUDED."workHistoryJson","skillsJson"=EXCLUDED."skillsJson","hidden"=EXCLUDED."hidden","order"=EXCLUDED."order","updatedAt"=NOW();

-- Rembo (THE ARCHITECT)
INSERT INTO "Member" ("slug","name","nick","role","img","color","highlight","bio","tagline","quote","funFactsJson","element","joinYear","statsJson","socialsJson","taglineCareer","location","availability","educationJson","workHistoryJson","skillsJson","hidden","order","createdAt","updatedAt") VALUES ('razka','Muhammad Razka Faudzan','Rembo','THE ARCHITECT','/members/member-razka.webp','bg-[#00e5ff]','text-[#00e5ff]','Perancang struktur di balik kekacauan. **Setiap blueprint yang dia buat** ternyata jadi peta untuk petualangan yang tak terduga.','Designs the chaos others call home.','Setiap struktur yang aku bangun punya pintu rahasia. Itu bukan bug — itu feature.',$$["Bisa ngoding sambil denger podcast true crime","Arsip screenshot-nya punya 4000+ file","Selalu bawa charger cadangan ke mana-mana","Menghitung optimasi FPS sebelum beli HP"]$$,'ICE','2020',$$[{"label":"STR","value":"8"},{"label":"DEX","value":"14"},{"label":"CON","value":"12"},{"label":"INT","value":"18"},{"label":"WIS","value":"15"},{"label":"CHA","value":"16"}]$$,$$[{"label":"INSTAGRAM","href":"#"},{"label":"X_TWITTER","href":"#"},{"label":"DISCORD","href":"#"}]$$,'','','EMPLOYED',$$[]$$,$$[]$$,$$[]$$,false,1,NOW(),NOW()) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","nick"=EXCLUDED."nick","role"=EXCLUDED."role","img"=EXCLUDED."img","color"=EXCLUDED."color","highlight"=EXCLUDED."highlight","bio"=EXCLUDED."bio","tagline"=EXCLUDED."tagline","quote"=EXCLUDED."quote","funFactsJson"=EXCLUDED."funFactsJson","element"=EXCLUDED."element","joinYear"=EXCLUDED."joinYear","statsJson"=EXCLUDED."statsJson","socialsJson"=EXCLUDED."socialsJson","taglineCareer"=EXCLUDED."taglineCareer","location"=EXCLUDED."location","availability"=EXCLUDED."availability","educationJson"=EXCLUDED."educationJson","workHistoryJson"=EXCLUDED."workHistoryJson","skillsJson"=EXCLUDED."skillsJson","hidden"=EXCLUDED."hidden","order"=EXCLUDED."order","updatedAt"=NOW();

-- Eja (THE STRATEGIST)
INSERT INTO "Member" ("slug","name","nick","role","img","color","highlight","bio","tagline","quote","funFactsJson","element","joinYear","statsJson","socialsJson","taglineCareer","location","availability","educationJson","workHistoryJson","skillsJson","hidden","order","createdAt","updatedAt") VALUES ('reza','Reza','Eja','THE STRATEGIST','/members/member-reza.webp','bg-[#d4ff00]','text-[#d4ff00]','Pikirannya selalu lima langkah di depan. **Saat yang lain panik, dia sudah menyiapkan tiga rencana cadangan.**','Five moves ahead before you blink.','Rencana A gagal? Tenang. Aku punya rencana B sampai Z, dan dua di antaranya melibatkan ayam.',$$["Punya notes folder khusus berisi 'what-if scenarios'","Menang ranked 1v3 dengan strategi mind-game","Tidur 5 jam tapi terlihat segar (kecurigaan robot)","Pernah invalidate sebuah patch game dalam 30 menit"]$$,'MIND','2020',$$[{"label":"STR","value":"6"},{"label":"DEX","value":"12"},{"label":"CON","value":"10"},{"label":"INT","value":"20"},{"label":"WIS","value":"16"},{"label":"CHA","value":"13"}]$$,$$[{"label":"INSTAGRAM","href":"#"},{"label":"X_TWITTER","href":"#"},{"label":"DISCORD","href":"#"}]$$,'','','EMPLOYED',$$[]$$,$$[]$$,$$[]$$,false,2,NOW(),NOW()) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","nick"=EXCLUDED."nick","role"=EXCLUDED."role","img"=EXCLUDED."img","color"=EXCLUDED."color","highlight"=EXCLUDED."highlight","bio"=EXCLUDED."bio","tagline"=EXCLUDED."tagline","quote"=EXCLUDED."quote","funFactsJson"=EXCLUDED."funFactsJson","element"=EXCLUDED."element","joinYear"=EXCLUDED."joinYear","statsJson"=EXCLUDED."statsJson","socialsJson"=EXCLUDED."socialsJson","taglineCareer"=EXCLUDED."taglineCareer","location"=EXCLUDED."location","availability"=EXCLUDED."availability","educationJson"=EXCLUDED."educationJson","workHistoryJson"=EXCLUDED."workHistoryJson","skillsJson"=EXCLUDED."skillsJson","hidden"=EXCLUDED."hidden","order"=EXCLUDED."order","updatedAt"=NOW();

-- Byan (THE VANGUARD)
INSERT INTO "Member" ("slug","name","nick","role","img","color","highlight","bio","tagline","quote","funFactsJson","element","joinYear","statsJson","socialsJson","taglineCareer","location","availability","educationJson","workHistoryJson","skillsJson","hidden","order","createdAt","updatedAt") VALUES ('abyan','Muhammad Abyan Riyadh Amal','Byan','THE VANGUARD','/members/member-abyan.webp','bg-[#ff00ff]','text-[#ff00ff]','Barisan depan yang tak pernah mundur. **Kalau ada tembok, dia yang duluan nubruk** — dan biasanya temboknya yang kalah.','Runs headfirst. Walls lose.','Pikir dulu itu nanti. Sekarang, charge!',$$["Pernah push tower sendirian dan menang","Reaksi dodge creeper: 0.2 detik","Koleksi skin game lebih mahal dari motor","Motto: 'lebih baik regret daripada penasaran'"]$$,'STORM','2020',$$[{"label":"STR","value":"18"},{"label":"DEX","value":"14"},{"label":"CON","value":"17"},{"label":"INT","value":"8"},{"label":"WIS","value":"7"},{"label":"CHA","value":"10"}]$$,$$[{"label":"INSTAGRAM","href":"#"},{"label":"X_TWITTER","href":"#"},{"label":"DISCORD","href":"#"}]$$,'','','EMPLOYED',$$[]$$,$$[]$$,$$[]$$,false,3,NOW(),NOW()) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","nick"=EXCLUDED."nick","role"=EXCLUDED."role","img"=EXCLUDED."img","color"=EXCLUDED."color","highlight"=EXCLUDED."highlight","bio"=EXCLUDED."bio","tagline"=EXCLUDED."tagline","quote"=EXCLUDED."quote","funFactsJson"=EXCLUDED."funFactsJson","element"=EXCLUDED."element","joinYear"=EXCLUDED."joinYear","statsJson"=EXCLUDED."statsJson","socialsJson"=EXCLUDED."socialsJson","taglineCareer"=EXCLUDED."taglineCareer","location"=EXCLUDED."location","availability"=EXCLUDED."availability","educationJson"=EXCLUDED."educationJson","workHistoryJson"=EXCLUDED."workHistoryJson","skillsJson"=EXCLUDED."skillsJson","hidden"=EXCLUDED."hidden","order"=EXCLUDED."order","updatedAt"=NOW();

-- Acong (THE MAVERICK)
INSERT INTO "Member" ("slug","name","nick","role","img","color","highlight","bio","tagline","quote","funFactsJson","element","joinYear","statsJson","socialsJson","taglineCareer","location","availability","educationJson","workHistoryJson","skillsJson","hidden","order","createdAt","updatedAt") VALUES ('rasya','Rasya Musyafa Ridwan','Acong','THE MAVERICK','/members/member-rasya.webp','bg-[#ff8c00]','text-[#ff8c00]','Yang tak pernah bisa ditebak. **Strateginya? Tidak ada.** Dan itu justru strategi paling mematikan yang pernah ada.','No plan. That''s the plan.','Kalau musuh bisa nebak langkahku, berarti aku belum cukup random.',$$["Pernah menang tournament pake pick random","Punya 12 meme yang hanya dimengerti circle ini","Spontan ngajak roadtrip tengah malam — berkali-kali","Quote-nya di-pin di 5 server discord berbeda"]$$,'CHAOS','2020',$$[{"label":"STR","value":"10"},{"label":"DEX","value":"18"},{"label":"CON","value":"12"},{"label":"INT","value":"14"},{"label":"WIS","value":"12"},{"label":"CHA","value":"13"}]$$,$$[{"label":"INSTAGRAM","href":"#"},{"label":"X_TWITTER","href":"#"},{"label":"DISCORD","href":"#"}]$$,'','','EMPLOYED',$$[]$$,$$[]$$,$$[]$$,false,4,NOW(),NOW()) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","nick"=EXCLUDED."nick","role"=EXCLUDED."role","img"=EXCLUDED."img","color"=EXCLUDED."color","highlight"=EXCLUDED."highlight","bio"=EXCLUDED."bio","tagline"=EXCLUDED."tagline","quote"=EXCLUDED."quote","funFactsJson"=EXCLUDED."funFactsJson","element"=EXCLUDED."element","joinYear"=EXCLUDED."joinYear","statsJson"=EXCLUDED."statsJson","socialsJson"=EXCLUDED."socialsJson","taglineCareer"=EXCLUDED."taglineCareer","location"=EXCLUDED."location","availability"=EXCLUDED."availability","educationJson"=EXCLUDED."educationJson","workHistoryJson"=EXCLUDED."workHistoryJson","skillsJson"=EXCLUDED."skillsJson","hidden"=EXCLUDED."hidden","order"=EXCLUDED."order","updatedAt"=NOW();

-- Tipki (THE ENIGMA)
INSERT INTO "Member" ("slug","name","nick","role","img","color","highlight","bio","tagline","quote","funFactsJson","element","joinYear","statsJson","socialsJson","taglineCareer","location","availability","educationJson","workHistoryJson","skillsJson","hidden","order","createdAt","updatedAt") VALUES ('rifqi','Muhammad Rifqi','Tipki','THE ENIGMA','','bg-[#00ff00]','text-[#00ff00]','Misteri berjalan. **Kadang hadir, kadang hilang**, tapi selalu muncul tepat saat dibutuhkan. Seperti glitch di matriks.','Here when it matters. Gone otherwise.','Online status-ku tidak mencerminkan realita. Aku selalu ada — di latar.',$$["Pernah ghosting 3 bulan lalu balik seolah tak terjadi apa-apa","Punya 6 alias di platform berbeda","Reaction time-nya konstan di bawah 150ms (dicurigai AI)","Hanya muncul di chat saat ada yang butuh di-save"]$$,'VOID','2020',$$[{"label":"STR","value":"12"},{"label":"DEX","value":"16"},{"label":"CON","value":"14"},{"label":"INT","value":"13"},{"label":"WIS","value":"18"},{"label":"CHA","value":"8"}]$$,$$[{"label":"INSTAGRAM","href":"#"},{"label":"X_TWITTER","href":"#"},{"label":"DISCORD","href":"#"}]$$,'','','EMPLOYED',$$[]$$,$$[]$$,$$[]$$,false,5,NOW(),NOW()) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","nick"=EXCLUDED."nick","role"=EXCLUDED."role","img"=EXCLUDED."img","color"=EXCLUDED."color","highlight"=EXCLUDED."highlight","bio"=EXCLUDED."bio","tagline"=EXCLUDED."tagline","quote"=EXCLUDED."quote","funFactsJson"=EXCLUDED."funFactsJson","element"=EXCLUDED."element","joinYear"=EXCLUDED."joinYear","statsJson"=EXCLUDED."statsJson","socialsJson"=EXCLUDED."socialsJson","taglineCareer"=EXCLUDED."taglineCareer","location"=EXCLUDED."location","availability"=EXCLUDED."availability","educationJson"=EXCLUDED."educationJson","workHistoryJson"=EXCLUDED."workHistoryJson","skillsJson"=EXCLUDED."skillsJson","hidden"=EXCLUDED."hidden","order"=EXCLUDED."order","updatedAt"=NOW();

-- Dudit (THE CATALYST)
INSERT INTO "Member" ("slug","name","nick","role","img","color","highlight","bio","tagline","quote","funFactsJson","element","joinYear","statsJson","socialsJson","taglineCareer","location","availability","educationJson","workHistoryJson","skillsJson","hidden","order","createdAt","updatedAt") VALUES ('dudit','Raditya Jundika Putra','Dudit','THE CATALYST','','bg-[#8a2be2]','text-[#8a2be2]','Elemen yang mempercepat reaksi. **Tanpa dia, semuanya akan berjalan lambat.** Dengan dia, semuanya jadi ledakan.','Accelerator of every reaction.','Aku bukan pemicu masalah. Aku cuma yang bikin semuanya jadi lebih cepat — termasuk kelar-nya.',$$["Pernah convert 3 orang jadi main game baru dalam sehari","Menyebar rekomendasi anime lebih cepat dari algoritma","Penemu 'meta baru' yang 80% akurat","Tanggung jawab atas 60% drama server"]$$,'ENERGY','2020',$$[{"label":"STR","value":"10"},{"label":"DEX","value":"8"},{"label":"CON","value":"14"},{"label":"INT","value":"14"},{"label":"WIS","value":"18"},{"label":"CHA","value":"16"}]$$,$$[{"label":"INSTAGRAM","href":"#"},{"label":"X_TWITTER","href":"#"},{"label":"DISCORD","href":"#"}]$$,'','','EMPLOYED',$$[]$$,$$[]$$,$$[]$$,false,6,NOW(),NOW()) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","nick"=EXCLUDED."nick","role"=EXCLUDED."role","img"=EXCLUDED."img","color"=EXCLUDED."color","highlight"=EXCLUDED."highlight","bio"=EXCLUDED."bio","tagline"=EXCLUDED."tagline","quote"=EXCLUDED."quote","funFactsJson"=EXCLUDED."funFactsJson","element"=EXCLUDED."element","joinYear"=EXCLUDED."joinYear","statsJson"=EXCLUDED."statsJson","socialsJson"=EXCLUDED."socialsJson","taglineCareer"=EXCLUDED."taglineCareer","location"=EXCLUDED."location","availability"=EXCLUDED."availability","educationJson"=EXCLUDED."educationJson","workHistoryJson"=EXCLUDED."workHistoryJson","skillsJson"=EXCLUDED."skillsJson","hidden"=EXCLUDED."hidden","order"=EXCLUDED."order","updatedAt"=NOW();

-- Naye (THE PHANTOM) [HIDDEN]
INSERT INTO "Member" ("slug","name","nick","role","img","color","highlight","bio","tagline","quote","funFactsJson","element","joinYear","statsJson","socialsJson","taglineCareer","location","availability","educationJson","workHistoryJson","skillsJson","hidden","order","createdAt","updatedAt") VALUES ('nayla','Nayla','Naye','THE PHANTOM','','bg-[#ff006e]','text-[#ff006e]','Entitas misterius yang muncul hanya saat chaos mode aktif. **Hadir di bayang-bayang**, namun selalu ada saat dibutuhkan.','Here when chaos calls. Gone when it fades.','Aku bukan glitch. Aku fitur yang belum kamu temukan.',$$["Muncul hanya dalam chaos mode","Identitas sebenarnya tidak ada yang tahu","Selalu hadir saat konami code diaktifkan","Lebih mirip hantu daripada member"]$$,'PHANTOM','2026',$$[{"label":"STR","value":"10"},{"label":"DEX","value":"20"},{"label":"CON","value":"8"},{"label":"INT","value":"18"},{"label":"WIS","value":"16"},{"label":"CHA","value":"20"}]$$,$$[{"label":"INSTAGRAM","href":"#"},{"label":"X_TWITTER","href":"#"},{"label":"DISCORD","href":"#"}]$$,'','','EMPLOYED',$$[]$$,$$[]$$,$$[]$$,true,7,NOW(),NOW()) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","nick"=EXCLUDED."nick","role"=EXCLUDED."role","img"=EXCLUDED."img","color"=EXCLUDED."color","highlight"=EXCLUDED."highlight","bio"=EXCLUDED."bio","tagline"=EXCLUDED."tagline","quote"=EXCLUDED."quote","funFactsJson"=EXCLUDED."funFactsJson","element"=EXCLUDED."element","joinYear"=EXCLUDED."joinYear","statsJson"=EXCLUDED."statsJson","socialsJson"=EXCLUDED."socialsJson","taglineCareer"=EXCLUDED."taglineCareer","location"=EXCLUDED."location","availability"=EXCLUDED."availability","educationJson"=EXCLUDED."educationJson","workHistoryJson"=EXCLUDED."workHistoryJson","skillsJson"=EXCLUDED."skillsJson","hidden"=EXCLUDED."hidden","order"=EXCLUDED."order","updatedAt"=NOW();

-- GUESTBOOK
INSERT INTO "GuestbookEntry" ("name","message","color","approved","createdAt") SELECT * FROM (VALUES
  ('Wanderer_07','Across dimensions, the orbit holds. Salam chaos dari ujung galaksi.','#ff4d4d',true,NOW()),
  ('Pixel Phantom','Situs ini bikin nostalgia SMK banget. Neo-brutalism for the win.','#00e5ff',true,NOW()),
  ('Orbit Guest','Seven souls, one gravity. Tetap bersama walau terpisah ratusan parsec.','#d4ff00',true,NOW()),
  ('Void Walker','Gallery of Chaos lives up to its name. Loved every frame.','#ff00ff',true,NOW())
) AS t("name","message","color","approved","createdAt") WHERE NOT EXISTS (SELECT 1 FROM "GuestbookEntry" LIMIT 1);

-- NEWS (seed only if empty)
INSERT INTO "NewsArticle" ("title","body","category","author","pinned","createdAt") SELECT * FROM (VALUES
  ('UNDIMENSION V3 LAUNCHED','Versi 3 dari situs UNDIMENSION sudah live. Banyak fitur baru.','UPDATE','THE COLLECTIVE',true,NOW()),
  ('EVENT NOSTALGIA SMK 2026','Reuni angkatan diadakan bulan depan.','EVENT','ALDI',false,NOW() - INTERVAL '1 day'),
  ('CHAOS MODE UNLOCKED','Konami code aktif. Masukkan: ↑↓←→←←↑ untuk chaos mode.','CHAOS','THE COLLECTIVE',false,NOW() - INTERVAL '2 days')
) AS t("title","body","category","author","pinned","createdAt") WHERE NOT EXISTS (SELECT 1 FROM "NewsArticle" LIMIT 1);

COMMIT;
-- ✅ Seed: 8 members + 4 guestbook + 3 news.

